### ISSUE TITLE
ImportError: No module named 'pysimgrid.simdag.algorithms

### ISSUE THREAD

**Issue by nikosT** [alexmnazarenko/pysimgrid#14]
I'm trying to run the example code/simulation and I get the error:

`ImportError: No module named 'pysimgrid.simdag.algorithms'
`

Could you also provide a more extensive guide?
Thank you!!

**Comment by alexmnazarenko** [comment]
Hey,

I believe it's the same problem with installation I should have fixed a
while ago (e.g. https://github.com/alexmnazarenko/pysimgrid/issues/12).

Try running from 'inplace' build of pysimgrid:

```bash
cd pysimgrid_repo
python3 setup.py build_ext --inplace
python3 basic_test.py
```

Let me know if it works for you.

I've recently moved to a new job, still struggling to find time to clean up
this installation mess :-)

--
WBR,
Alexey

**Comment by nikosT** [comment]
Yes, it worked! But I also have to have my python file inside the  pysimgrid_repo.
